export const SET_SYSTEM_DATE_ERROR = 'SET_SYSTEMDATE_ERROR';
export const SET_SYSTEM_DATE_SUCCESS = 'SET_SYSTEMDATE_SUCCESS';
export const SET_SYSTEM_DATE_LOADING = 'SET_SYSTEMDATE_LOADING';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const SET_LICENSE_WARNING_ERROR = 'SET_LICENSE_WARNING_ERROR';
export const SET_LICENSE_WARNING_SUCCESS = 'SET_LICENSE_WARNING_SUCCESS';
export const SET_LICENSE_WARNING_LOADING = 'SET_LICENSE_WARNING_LOADING';

export const SET_TABLE_LIST_ERROR = 'SET_TABLE_LIST_ERROR';
export const SET_TABLE_LIST_SUCCESS = 'SET_TABLE_LIST_SUCCESS';
export const SET_TABLE_LIST_LOADING = 'SET_TABLE_LIST_LOADING';

export const RETRIEVE_ERROR_LOG_SUCCESS = 'RETRIEVE_ERROR_LOG_SUCCESS';
export const RETRIEVE_ERROR_LOG_ERROR = 'RETRIEVE_ERROR_LOG_ERROR';
export const RETRIEVE_ERROR_LOG_LOADING = 'RETRIEVE_ERROR_LOG_LOADING';

export const RETRIEVE_FEATURE_LIST_SUCCESS = 'RETRIEVE_FEATURE_LIST_SUCCESS';
export const RETRIEVE_FEATURE_LIST_ERROR = 'RETRIEVE_FEATURE_LIST_ERROR';
export const RETRIEVE_FEATURE_LIST_LOADING = 'RETRIEVE_FEATURE_LIST_LOADING';

export const RETRIEVE_ADMIN_LOG_SUCCESS = 'RETRIEVE_ADMIN_LOG_SUCCESS';
export const RETRIEVE_ADMIN_LOG_ERROR = 'RETRIEVE_ADMIN_LOG_ERROR';
export const RETRIEVE_ADMIN_LOG_LOADING = 'RETRIEVE_ADMIN_LOG_LOADING';

export const RETRIEVE_ADMIN_LOG_EMPLOYEE_LIST_SUCCESS = 'RETRIEVE_ADMIN_LOG_EMPLOYEE_LIST_SUCCESS';
export const RETRIEVE_ADMIN_LOG_EMPLOYEE_LIST_ERROR = 'RETRIEVE_ADMIN_LOG_EMPLOYEE_LIST_ERROR';
export const RETRIEVE_ADMIN_LOG_EMPLOYEE_LIST_LOADING = 'RETRIEVE_ADMIN_LOG_EMPLOYEE_LIST_LOADING';

export const RETRIEVE_PATIENT_LIST_SUCCESS = 'RETRIEVE_PATIENT_LIST_SUCCESS';
export const RETRIEVE_PATIENT_LIST_ERROR = 'RETRIEVE_PATIENT_LIST_ERROR';
export const RETRIEVE_PATIENT_LIST_LOADING = 'RETRIEVE_PATIENT_LIST_LOADING';

export const RETRIEVE_ADMIN_LOG_PATIENT_SUCCESS = 'RETRIEVE_ADMIN_LOG_PATIENT_SUCCESS';
export const RETRIEVE_ADMIN_LOG_PATIENT_ERROR = 'RETRIEVE_ADMIN_LOG_PATIENT_ERROR';
export const RETRIEVE_ADMIN_LOG_PATIENT_LOADING = 'RETRIEVE_ADMIN_LOG_PATIENT_LOADING';